#!/bin/bash
PKGMGR=/bin/yum
if ! [ -e $PKGMGR ]; then
  PKGMGR=apt

fi
if ! [ -e $PKGMGR ]; then
PKGMGR=zypper
fi

$PKGMGR install -y ansible
test -e /provisioner || mkdir /provisioner
if [ -f /etc/ansiblenfs.cfg ]; then
  ANSIBLENFSMOUNT=$( grep MOUNT: /etc/ansiblenfs.cfg | sed 's/MOUNT:[ \t]*//' )
  ANSIBLENFSDIR=$( grep DIR: /etc/ansiblenfs.cfg | sed 's/DIR:[ \t]*//' )
  mount -t nfs -overs=3,ro "$ANSIBLENFSMOUNT" /provisioner
  cd "/provisioner/$ANSIBLENFSDIR"
  ansible-playbook node-startup.yml
fi
sleep 1
umount /provisioner
