#!/bin/bash
exec >/tmp/cyclecloud.log 2>&1
PKGMGR=/bin/yum
if ! [ -e $PKGMGR ]; then
  PKGMGR=apt

fi
if ! [ -e $PKGMGR ]; then
PKGMGR=zypper
fi

if grep -q "elease 7" /etc/centos-release  ; 
then
  /bin/rm -f /etc/yum.repos.d/Cent*
  curl -L  https://raw.githubusercontent.com/securelinx/cyclecloud/main/artefacts/CENTOS7-VAULT.repo > /etc/yum.repos.d/CENTOS7-VAULT.repo
  sed -i 's/^\(metalink.*\)$/#\1/; s/^#\(baseurl.*\)$/\1/; s#http://download.fedoraproject.org/pub/epel/7/#https://dl.fedoraproject.org/pub/archive/epel/7.9/#' /etc/yum.repos.d/epel.repo
  $PKGMGR -y install nfs-utils'
fi

$PKGMGR install -y ansible
test -e /provisioner || mkdir /provisioner
if [ -f /etc/ansiblenfs.cfg ]; then
  ANSIBLENFSMOUNT=$( grep MOUNT: /etc/ansiblenfs.cfg | sed 's/MOUNT:[ \t]*//' )
  ANSIBLENFSDIR=$( grep DIR: /etc/ansiblenfs.cfg | sed 's/DIR:[ \t]*//' )
else
 function get_cloudconfig_string ()
 {
   temp=$(grep ^"$1":  /var/lib/cloud/instance/user-data.txt | awk '{print $2}' | tail -1)
   temp="${temp%\"}"
   temp="${temp#\"}"
   temp="${temp%\'}"
   temp="${temp#\'}"
   echo "$temp"
 }
 ANSIBLENFSMOUNT=$(get_cloudconfig_string  nfsmaster)
 ANSIBLENFSDIR=$(get_cloudconfig_string  sharedconfig_dir) 
fi
mount -t nfs -overs=3,ro "$ANSIBLENFSMOUNT" /provisioner
cd "/provisioner/$ANSIBLENFSDIR"
mkdir "/provisioner/initlogs/$(hostname -s)"

#run public startups for all hpc - this is on github
ansible-playbook generic-node-startup.yml

#run customer startup if exists - this isnt on github
if [ -f  customer-node-startup.yml ]; then 
  ansible-playbook customer-node-startup.yml
fi
mkdir -p "/provisioner/initlogs/$(hostname -s)"
cp /tmp/cyclecloud.log "/provisioner/initlogs/$(hostname -s)"
cd /
sleep 1

umount /provisioner || umount -fl /provisioner
sleep 5
echo complete
