---
- hosts: localhost
  name: firstruns
  #vars can be overriden in site_vars
  vars: 
      homebase: "/home"
      configurenis: false
      disable_networkmanager: false
  tasks:
     - file: 
         name: site_vars
         state: directory
     - include_vars:
         dir: site_vars
     - name: sudoers group
       group: 
          name: admins
          gid: 599
     - name: admin sudo
       copy:
          dest: /etc/sudoers.d/admins
          mode: "0600"
          content: |
            %admins ALL=(ALL) NOPASSWD:ALL
            Defaults:%admins !requiretty
          
     - name: "Added securelinx user"
       user:
          name: securelinx
          shell: /bin/bash
          group: admins
          uid: 599
          home: "{{ homebase }}/securelinx"
          create_home: no
     - name: packages
       ansible.builtin.package:
          name:  [lvm2, tcsh,  mlocate, xauth, screen, environment-modules, rsync]
          state: present
    # Create the /mnt/resource directory and ensure it is world writable.  
    # There are no checks to ensure this is actually a large ssd and not the root fielsystem
     - name: Create /mnt/resource directory on all nodes - assumes this is normally a large ssd.
       file:
         state: directory
         mode: "1777"
         path: "/mnt/resource"
     - name: scratch symbolic link
       file:
         src: "/mnt/resource"
         dest: "/localscratch"
         state: link
     - name: ssh_config_user_skel
       file:
          path: /etc/skel/.ssh
          state: directory
     - name: ssh_config_user
       copy:
          dest: /etc/skel/.ssh/config
          content: | 
                host * 
                  CheckHostIP no
                  StrictHostKeyChecking no
                  UserKnownHostsFile /dev/null
     - name: setup nis
       include_role:
          name:  nis_client
       when: configurenis|default(false)|bool  == true
     - name: Change file ownership, group and permissions
       ansible.builtin.file:
         path: /mnt/resource
         owner: root
         group: root
         mode: '1777'     
     - name: Ensure munge is restarted
       ansible.builtin.service:
         name: munge
         state: restarted
